### ISSUE TITLE
It seems like a ton of unnecessary levels are being created with every makeTree() call

### ISSUE THREAD

**Issue by Sossenbinder** [Tierion/merkle-tools#2]
Hello,

I just started reading myself into your library, and in order to understand your tree generation, I wrote myself a quick output for the whole tree, which logs every levels amount of elements which is being used so far.

(I used this snippet:

        var index = 0;
        while(tree.levels[index] != undefined)
        {
            console.log("Levels [" + index + "]: " + tree.levels[index].length);
            ++index;
        }
)

However, I noticed that the code is producing a ton of (in my understanding) unnecessary levels. I always added one new leaf before making a new tree.

1 Element leads to one level (0) with 1 element -> fine

Everything from here on is looking weird to me

2 Elements lead to 3 levels, with 0 now containing the hash of the two elements at level 1. However, a third level with 2 elements is added as well.

3 Elements lead to, again, 3 correct levels from level 0 to 2, however, there are 3 additional levels, which seem to contain no useful information, while only the last one seems to contain the leaf data, according to a function where the last level is being used to read out the leaves.

I didn't read myself in deep enough, but I would say the "junk" levels are a remainder of the shifting which is done on the level array when making a new tree. An easy solution might be to calculate the number of levels with the help of the leaf count, and to pop everything beyond that.

However, I'm not quite sure if this is intended or not, or if it's just my misunderstanding of your code

**Comment by jasonbukowski** [comment]
Is it possible that you are not reseting the tree between each makeTree() call? That may cause the results you are seeing. The tree must be reset (cleared) between each makeTree() call. You cannot currently append new leaves to an existing, already built tree and then call makeTree() again. If this is the case in your situation, perhaps something can be changed here to allow this behavior.

**Comment by Sossenbinder** [comment]
Thanks a lot, I didn't know I have to reset it before calling makeTree(). Now the behaviour is as I expected it to be.

**Comment by jasonbukowski** [comment]
Glad to hear that its working well for you now. I will consider adding something in the future to allow rebuilding without resetting the tree to prevent you and others from encountering this issue again.
